flashfiles: remove duplicated emmc definition
group.emmc group definition is defined twice in flashfiles.ini files.
Removing second and unnecessary redefinition of emmc group.

Change-Id: Ic293dcde94f4e161e575b218ab16f174aa849dcd
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-4402
Signed-off-by: Tony Raveneau <tonyx.raveneau@intel.com>
Reviewed-on: https://android.intel.com:443/420508