iwlwifi: Re-enable build from source using Android.mk
Kernel build from source re-introduced iwlwifi driver compilation
using directly Makefiles This patch is changing the compilation method
from Makefile to Android.mk : this is the expected way of building for
WCS.
In addition, it fixes the compilation error in the modules_install
using Makefiles method

Revert also -01 option patch done for iwlwifi compilation on sofia

Change-Id: Ifc761af061c13a676e728d7f8cf945f270abe668
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-4551
Signed-off-by: Jean-Michel Bachot <jean-michel.bachot@intel.com>
Reviewed-on: https://android.intel.com:443/424612